import Home from "../components/home/Home";
import Head from "next/head";
const Camperock = function () {
  return (
    <>
      <Home />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Camperock;
